theme: jekyll-theme-minimal
title: Emily Eikey's Webpage
description: Visualization Class Demo
show_downloads: True
navigation:
  - title: PZA Uptake Plot
    url: /pza.html
  - title: Isoniazid Uptake Plot
    url: /isoniazid.html
